# Kotlin
kotlinVersion=2.3.0

# Spring Boot
springBootVersion=3.4.1
springDependencyManagementVersion=1.1.7

# Kotest
kotestVersion=6.0.7

# MockK
mockkVersion=1.13.16

# Redisson
redissonVersion=3.42.0

# Project
group=com.karrot.zeronine
version=0.0.1-SNAPSHOT

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
