apiVersion: apps/v1
kind: Deployment
metadata:
  name: karrot-batch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karrot-batch
  template:
    metadata:
      labels:
        app: karrot-batch
    spec:
      containers:
        - name: karrot-batch
          image: karrot-zeronine-batch:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/karrot_zeronine
            - name: SPRING_DATASOURCE_USERNAME
              value: karrot
            - name: SPRING_DATASOURCE_PASSWORD
              value: karrot123
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: REDISSON_SINGLESERVERCONFIG_ADDRESS
              value: redis://redis:6379
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
